# Generated by Django 5.2 on 2025-04-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_job', '0002_alter_tag_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='job_type',
            field=models.CharField(choices=[('Full Time employment', 'Full Time employment'), ('Part Time employment', 'Part Time employment'), ('Apprenticeship', 'Apprenticeship'), ('Internship', 'Internship'), ('Traineeship', 'Traineeship'), ('Contract employment', 'Contract employment'), ('Casual employment', 'Casual employment'), ('Seasonal employment', 'Seasonal employment'), ('Employment on commission', 'Employment on commission'), ('Leased employment', 'Leased employment'), ('Contingent employment', 'Contingent employment'), ('Probation', 'Probation')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post_job.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
