# Generated by Django 5.2 on 2025-04-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_job', '0003_remove_post_content_post_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='experience_level',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Entry-level', 'Entry-level'), ('Mid-level', 'Mid-level'), ('Senior-level', 'Senior-level'), ('Manager', 'Manager'), ('Director', 'Director')], default='Fresher', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='industry',
            field=models.CharField(blank=True, choices=[('Information Technology', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Marketing', 'Marketing'), ('Engineering', 'Engineering'), ('Retail', 'Retail'), ('Customer Service', 'Customer Service'), ('Legal', 'Legal')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='work_environment',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_type',
            field=models.CharField(choices=[('Full Time employment', 'Full Time employment'), ('Part Time employment', 'Part Time employment'), ('Apprenticeship', 'Apprenticeship'), ('Internship', 'Internship'), ('Traineeship', 'Traineeship'), ('Contract employment', 'Contract employment'), ('Casual employment', 'Casual employment'), ('Seasonal employment', 'Seasonal employment'), ('Employment on commission', 'Employment on commission'), ('Leased employment', 'Leased employment'), ('Contingent employment', 'Contingent employment'), ('Probation', 'Probation'), ('Freelance', 'Freelance'), ('Temporary', 'Temporary')], default='None', max_length=100),
        ),
    ]
