# Generated by Django 5.2 on 2025-04-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_job', '0004_post_experience_level_post_industry_post_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.CharField(blank=True, choices=[('Below 30K', 'Below 30K'), ('30K-50K', '30K-50K'), ('50K-80K', '50K-80K'), ('80K-100K', '80K-100K'), ('100K+', '100K+')], null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Django', 'Django'), ('React', 'React'), ('SQL', 'SQL'), ('Java', 'Java'), ('C#', 'C#'), ('AWS', 'AWS'), ('Docker', 'Docker'), ('Machine Learning', 'Machine Learning'), ('Data Analysis', 'Data Analysis'), ('UI/UX Design', 'UI/UX Design'), ('SEO', 'SEO'), ('Graphic Design', 'Graphic Design')], max_length=255, unique=True),
        ),
    ]
