# Generated by Django 5.2 on 2025-04-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_job', '0005_alter_post_salary_alter_tag_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='skill_tag',
        ),
    ]
